### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by yishenggudou** [isaacl/meliae#1]
I Just install `meliae` on my cestos

```
git clone git@github.com:isaacl/meliae.git
cd meliae
python setup.py install
python -c "from meliae import scannr"
```

got a error
![image](https://f.cloud.github.com/assets/380657/2364222/9c069a2c-a665-11e3-85da-ca90e8178f1a.png)

**Comment by jameinel** [comment]
It would be "scanner" you are missing the "e"

John
=:->

**Comment by yishenggudou** [comment]
^_^ thanks
