### ISSUE TITLE
py3 support?

### ISSUE THREAD

**Issue by psy2013GitHub** [isaacl/meliae#2]
hi, this is really a great tool.
but is there any future plan for support of python3?
thanks

**Comment by cwei-bgl** [comment]
Very useful tool. Also used by pyrasite, but can't be used in python3, as a simple language change.

Collecting meliae
  Using cached https://files.pythonhosted.org/packages/98/c6/7fa12062ddfe1732d43b34b64a3fe99da958a88fa1d8b7550fe386a9ca01/meliae-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w1/b0b45s5d6k3fhqdxqbmsd3qm0000gn/T/pip-install-kkmej34p/meliae/setup.py", line 67
        print "We require Cython to be installed."
                                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("We require Cython to be installed.")?

**Comment by frankforp** [comment]
I also have the similar issues when installed the pyrasite under "Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32"
I am not sure if the pyrasite could support the py3.6.6.

**Comment by Duiesel** [comment]
Same to me.
Seems that supporting project has been stopped. =(

**Comment by jelmer** [comment]
Note that this is not the official project homepage, that is at https://launchpad.net/meliae (although also stale).

**Comment by freecui** [comment]
Same to me

**Comment by cztchoice** [comment]
just a hint:

Greg Banks  have some work on python3

https://code.launchpad.net/~greg-n-banks/meliae/python3

**Comment by jameinel** [comment]
We just released 0.5.0 with Python 3 support thanks to Colin Watson. I haven't been tracking issues here.
You're certainly welcome to follow greg'as work. At one point he was going to propose once he had tests passing, but fortunately the test suite passes now with both python 2.7 and 3.4-3.8.
